-- MySQL Script generated by MySQL Workbench
-- Qui 18 Ago 2016 23:05:36 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema centr089_centraljogos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema centr089_centraljogos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `centr089_centraljogos` DEFAULT CHARACTER SET utf8 ;
USE `centr089_centraljogos` ;

-- -----------------------------------------------------
-- Table `centr089_centraljogos`.`tb_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centr089_centraljogos`.`tb_permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_perm` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome_perm` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centr089_centraljogos`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centr089_centraljogos`.`tb_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_usu` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `flag_ativo` INT NOT NULL,
  `criado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `modificado` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `tb_permissao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_usuario_tb_permissao1_idx` (`tb_permissao_id` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_tb_usuario_tb_permissao1`
    FOREIGN KEY (`tb_permissao_id`)
    REFERENCES `centr089_centraljogos`.`tb_permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centr089_centraljogos`.`tb_regional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centr089_centraljogos`.`tb_regional` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_reg` VARCHAR(45) NOT NULL,
  `flag_ativo` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome_reg` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centr089_centraljogos`.`tb_cambista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centr089_centraljogos`.`tb_cambista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_camb` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `limite_diario` DECIMAL(10,2) NOT NULL,
  `limite_individual` DECIMAL(10,2) NOT NULL,
  `comissao1` DOUBLE NOT NULL,
  `comissao2` DOUBLE NOT NULL,
  `comissao3` DOUBLE NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tb_regional_id` INT NOT NULL,
  `flag_ativo` INT NOT NULL,
  `criado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `modificado` VARCHAR(45) NULL DEFAULT 'NULL ON UPDATE CURRENT_TIMESTAMP',
  PRIMARY KEY (`id`),
  INDEX `fk_tb_cambista_tb_regional_idx` (`tb_regional_id` ASC),
  CONSTRAINT `fk_tb_cambista_tb_regional`
    FOREIGN KEY (`tb_regional_id`)
    REFERENCES `centr089_centraljogos`.`tb_regional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centr089_centraljogos`.`tb_cotacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centr089_centraljogos`.`tb_cotacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `casa` DECIMAL(10,2) NULL DEFAULT 0,
  `empate` DECIMAL(10,2) NULL DEFAULT 0,
  `fora` DECIMAL(10,2) NULL DEFAULT 0,
  `gol_meio` DECIMAL(10,2) NULL DEFAULT 0,
  `mais_2gm` DECIMAL(10,2) NULL DEFAULT 0,
  `menos_3gm` DECIMAL(10,2) NULL DEFAULT 0,
  `ambas_marcam` DECIMAL(10,2) NULL DEFAULT 0,
  `casa_empate` DECIMAL(10,2) NULL DEFAULT 0,
  `fora_empate` DECIMAL(10,2) NULL DEFAULT 0,
  `casa_marca` DECIMAL(10,2) NULL DEFAULT 0,
  `fora_marca` DECIMAL(10,2) NULL DEFAULT 0,
  `casa_ou_fora` DECIMAL(10,2) NULL DEFAULT 0,
  `casavence_foramarca` DECIMAL(10,2) NULL DEFAULT 0,
  `foravence_casamarca` DECIMAL(10,2) NULL DEFAULT 0,
  `casavence_zero` DECIMAL(10,2) NULL DEFAULT 0,
  `foravence_zero` DECIMAL(10,2) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centr089_centraljogos`.`tb_continente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centr089_centraljogos`.`tb_continente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_cont` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centr089_centraljogos`.`tb_pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centr089_centraljogos`.`tb_pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_pais` VARCHAR(45) NOT NULL,
  `tb_continente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_pais_tb_continente1_idx` (`tb_continente_id` ASC),
  CONSTRAINT `fk_tb_pais_tb_continente1`
    FOREIGN KEY (`tb_continente_id`)
    REFERENCES `centr089_centraljogos`.`tb_continente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centr089_centraljogos`.`tb_campeonato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centr089_centraljogos`.`tb_campeonato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_camp` VARCHAR(100) NOT NULL,
  `tb_pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_campeonato_tb_pais1_idx` (`tb_pais_id` ASC),
  CONSTRAINT `fk_tb_campeonato_tb_pais1`
    FOREIGN KEY (`tb_pais_id`)
    REFERENCES `centr089_centraljogos`.`tb_pais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centr089_centraljogos`.`tb_partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centr089_centraljogos`.`tb_partida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `flag_ativo` INT NULL DEFAULT 0,
  `flag_cancelado` INT NULL DEFAULT 0,
  `flag_finalizado` INT NULL DEFAULT 0,
  `data_hora` DATETIME NOT NULL,
  `time_casa_gols` INT NULL,
  `time_fora_gols` INT NULL,
  `tb_cotacao_id` INT NOT NULL,
  `tb_campeonato_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_partida_tb_cotacao1_idx` (`tb_cotacao_id` ASC),
  INDEX `fk_tb_partida_tb_campeonato1_idx` (`tb_campeonato_id` ASC),
  CONSTRAINT `fk_tb_partida_tb_cotacao1`
    FOREIGN KEY (`tb_cotacao_id`)
    REFERENCES `centr089_centraljogos`.`tb_cotacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_partida_tb_campeonato1`
    FOREIGN KEY (`tb_campeonato_id`)
    REFERENCES `centr089_centraljogos`.`tb_campeonato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centr089_centraljogos`.`tb_aposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centr089_centraljogos`.`tb_aposta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `flag_venceu` INT NULL,
  `flag_cancelado` INT NULL,
  `apostador` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `retorno` DECIMAL(10,2) NOT NULL,
  `flag_pago` INT NULL,
  `tb_cambista_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_aposta_tb_cambista1_idx` (`tb_cambista_id` ASC),
  CONSTRAINT `fk_tb_aposta_tb_cambista1`
    FOREIGN KEY (`tb_cambista_id`)
    REFERENCES `centr089_centraljogos`.`tb_cambista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centr089_centraljogos`.`tb_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centr089_centraljogos`.`tb_time` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_time` VARCHAR(100) NOT NULL,
  `tb_campeonato_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_time_tb_campeonato1_idx` (`tb_campeonato_id` ASC),
  CONSTRAINT `fk_tb_time_tb_campeonato1`
    FOREIGN KEY (`tb_campeonato_id`)
    REFERENCES `centr089_centraljogos`.`tb_campeonato` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centr089_centraljogos`.`tb_regional_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centr089_centraljogos`.`tb_regional_usuario` (
  `tb_regional_id` INT NOT NULL,
  `tb_usuario_id` INT NOT NULL,
  PRIMARY KEY (`tb_regional_id`, `tb_usuario_id`),
  INDEX `fk_tb_regional_has_tb_usuario_tb_usuario1_idx` (`tb_usuario_id` ASC),
  INDEX `fk_tb_regional_has_tb_usuario_tb_regional1_idx` (`tb_regional_id` ASC),
  CONSTRAINT `fk_tb_regional_has_tb_usuario_tb_regional1`
    FOREIGN KEY (`tb_regional_id`)
    REFERENCES `centr089_centraljogos`.`tb_regional` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_regional_has_tb_usuario_tb_usuario1`
    FOREIGN KEY (`tb_usuario_id`)
    REFERENCES `centr089_centraljogos`.`tb_usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centr089_centraljogos`.`tb_aposta_partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centr089_centraljogos`.`tb_aposta_partida` (
  `tb_aposta_id` INT NOT NULL,
  `tb_partida_id` INT NOT NULL,
  `modalidade_aposta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tb_aposta_id`, `tb_partida_id`),
  INDEX `fk_tb_aposta_has_tb_partida_tb_partida1_idx` (`tb_partida_id` ASC),
  INDEX `fk_tb_aposta_has_tb_partida_tb_aposta1_idx` (`tb_aposta_id` ASC),
  CONSTRAINT `fk_tb_aposta_has_tb_partida_tb_aposta1`
    FOREIGN KEY (`tb_aposta_id`)
    REFERENCES `centr089_centraljogos`.`tb_aposta` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_aposta_has_tb_partida_tb_partida1`
    FOREIGN KEY (`tb_partida_id`)
    REFERENCES `centr089_centraljogos`.`tb_partida` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centr089_centraljogos`.`tb_partida_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centr089_centraljogos`.`tb_partida_time` (
  `tb_partida_id` INT NOT NULL,
  `tb_time_id` INT NOT NULL,
  `ordem` INT NOT NULL,
  PRIMARY KEY (`tb_partida_id`, `tb_time_id`),
  INDEX `fk_tb_partida_has_tb_time_tb_time1_idx` (`tb_time_id` ASC),
  INDEX `fk_tb_partida_has_tb_time_tb_partida1_idx` (`tb_partida_id` ASC),
  CONSTRAINT `fk_tb_partida_has_tb_time_tb_partida1`
    FOREIGN KEY (`tb_partida_id`)
    REFERENCES `centr089_centraljogos`.`tb_partida` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_partida_has_tb_time_tb_time1`
    FOREIGN KEY (`tb_time_id`)
    REFERENCES `centr089_centraljogos`.`tb_time` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
